export default {
    id: 'HOMES-2114',
    url: '/belle',
    path: ['HOMES--1', 'HOMES-1158', 'HOMES-2114'],
    level: 2,
    nodeId: 'HOMES-2114',
    status: 'published',
    siteUrl: 'http://dev.homes-site.wn.bauer-media.net.au',
    urlName: 'belle',
    nodeName: 'Belle',
    parentID: 'HOMES-1158',
    siteCode: '56421E16-B4AB-417C-9645-A6A89644D4B4',
    siteName: 'homes',
    sortOrder: 16,
    contentYear: 2015,
    navIsHidden: 0,
    navRedirect: { Url: null, Mode: 2, Title: '', NodeId: null, NewWindow: false },
    contentMonth: 9,
    contentTitle: 'Belle',
    contentVideo: '',
    articleSource: 'Belle',
    nodeTypeAlias: 'BrandSection',
    moduleParentId: 'HOMES-2114',
    contentHasVideo: false,
    contentImageUrl:
        'https://d3lp4xedbqa8a5.cloudfront.net/s3/digital-cougar-assets/homes/2017/10/16/1508131321242_hero150115---rl---shopping-3-timeless-spaces-063v0.5-1.jpg',
    nodeDateIndexed: '2016-11-03T00:08:01.98Z',
    pageDateCreated: '2015-09-15T02:14:32.00Z',
    nodeTypeAliasPath: ['Page', 'Sections', 'Section', 'BrandSection'],
    contentAccessLevels: -1,
    pageMetaDescription:
        'The online home for Belle is on Homes To Love. Enter a world of luxury and cutting-edge home design. Discover the latest trends and explore the world’s most beautiful interiors.',
    pageExcludeFromSitemap: 0,
    contentFacebookImageUrl: { tags: [], source: '', credits: [] },
    pageExcludeDescendantsFromSitemap: 0,
    updated_at: '2016-11-03T00:08:00.132Z'
};
