#
# Config YAML 
#
# Installing Pre-Requisites for Docker - NodeJS
# NPM and Node Install on Machine-VM.
#
# npm set @bxm:registry http://npm.digital.bauer-media.net.au
#
# node --version
#
# npm install
#
# cd src
#
# npm rebuild node-sass --force
# 
# cat version.js
#
# npm run test:ci
#
#
