# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# ORBS

orbs:
  welcome: circleci/welcome-orb@0.4.1

# JOBS

jobs:
  job-one:
    machine:
      image: ubuntu-1604:202010-01
    steps:
      - run:
          name: "UBUNTU | NPM | NODEJS"
          command: echo "UBUNTU | NPM | NODEJS"
      - run:
          name: "NPM set" # NPM set
          command: npm set @bxm:registry http://npm.digital.bauer-media.net.au
      - run:
          name: "NPM Install"
          command: npm install
      - run:
          name: "Node Re-Build" # Node Re-build
          command: npm rebuild node-sass --force
      - run:
          name: "Node Version"
          command: node --version
      - run:
          name: "Cat Version"
          command: cat version.js



# WORKFLOWS

workflows:
  welcome:
    jobs:
      - job-one
      - welcome/run

### End ###
