# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# ORBS
orbs:
  welcome: circleci/welcome-orb@0.4.1
# JOBS
jobs:

  job-one:
    machine:
      image: ubuntu-1604:202010-01
    working_directory: ~/homes-site
    steps:
      - checkout
      - run:
          name: "UBUNTU | NPM | NODEJS"
          command: echo "UBUNTU | NPM | NODEJS";
      - run:
          name: "list path and dir"
          command: pwd; ls; id;
      - run:
          name: "Curl for NVM | NPM | NodeJS" # NVM Set
          command: curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash; source ~/.profile;
      - run:
          name: "NVM Install for NodeJS 10.19.0" # NVM install nodejs=10.19.0
          command: source ~/.profile; nvm install v10.19.0; nvm use v10.19.0
      - run:
          name: "NVM List / Un-Install" # nvm Un-Install
          command: nvm list; nvm uninstall v12.18.4;
      - run:
          name: "NPM Version" # NPM Version
          command: npm --version
      - run:
          name: "Node Version" # Node Version
          command: node --version
     # NPM Setting
      - run:
          name: "NPM Set" # NPM Set
          command: npm set @bxm:registry http://npm.digital.bauer-media.net.au


# WORKFLOWS
workflows:
  welcome:
    jobs:
      - job-one

### End ###
