# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# ORBS
orbs:
  welcome: circleci/welcome-orb@0.4.1
# JOBS
jobs:

  job-one:
    machine:
      image: ubuntu-1604:202010-01
    working_directory: ~/homes-site
    steps:
      - checkout
      - run: |
          echo "UBUNTU | NPM | NODEJS"
          pwd; ls; id;
          curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash;
          source ~/.profile
          nvm install v10.19.0
          nvm use v10.19.0; id          
          node --version


# WORKFLOWS
workflows:
  welcome:
    jobs:
      - job-one

### End ###
