# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# ORBS
orbs:
  welcome: circleci/welcome-orb@0.4.1

# JOBS
jobs:
  job-one:
    machine:
      image: ubuntu-1604:202010-01
    steps:
      - run:
          name: "UBUNTU | NPM | NODEJS"
          command: echo "UBUNTU | NPM | NODEJS"; pwd; ls -ltr;
      #- run:
      #    name: "Install appstream/xenial-backports" # sudo apt install appstream/xenial-backports
    #      command: sudo apt-get install appstream/xenial-backports
      - run:
          name: "NPM Set" # NPM Set
          command: npm set @bxm:registry http://npm.digital.bauer-media.net.au
      - run:
          name: "CAT - APT - GET"
          command: cat /etc/apt/sources.list.d/google-chrome.list; ls -ltr;
      - run:
          name: "apt-get NodeJS 10.19.0" # apt-get install nodejs=10.19.0
          command: sudo apt-get update; curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -; sudo apt-get install -y nodejs=10.19.0
      - run:
          name: "NPM Install" # NPM Install
          command: npm install
      - run:
          name: "NPM NODE Re-Build" # Node Re-build
          command: npm rebuild node-sass --force
      - run:
          name: "NPM Version" # NPM Version
          command: npm --version
      - run:
          name: "Node Version" # Node Version
          command: node --version
      - run:
          name: "Cat Version"
          command: echo "Version JS" # find / -type f -name version.js -ls 2>>/dev/null
      - run:
          name: "NPM RUN TEST" # npm run test:ci
          command: npm run test:ci

# WORKFLOWS
workflows:
  welcome:
    jobs:
      - job-one
      - welcome/run

### End ###
