# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# ORBS

orbs:
  welcome: circleci/welcome-orb@0.4.1

# JOBS

jobs:

  job-one:
    machine:
      image: ubuntu-1604:202010-01
    working_directory: ~/homes-site
    steps:
      - checkout
      - run: |
          echo "UBUNTU | NPM | NODEJS"
          cd src; pwd;
          echo "Switching to src dir (/home/circleci/homes-site/src) ...."
          curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
          source ~/.profile
          nvm install v10.19.0
          nvm use v10.19.0;
          echo "Report NVM and NPM Version"
          node --version
          npm --version
          echo "Set BXM Registry ... "
          npm set @bxm:registry http://npm.digital.bauer-media.net.au
          npm install
          npm rebuild node-sass --force
          npm run test:ci

# WORKFLOWS

workflows:
  welcome:
    jobs:
      - job-one

### End ###
