var article_widget = {

    dateText: '.article__header .article__date-created',
    longTitle: 'h1.article__title',
    shortTeaser: '.article__summary',
    bodyParagraph: '.content-body__paragraph',
    bodyList: '.content-body__list',
    bodyHeading: '.content-body__heading',
    bodyImg: '.content-body__inline-image--landscape figure picture',
    relatedContentHeading: '.related-content .related-content__heading',
    relatedContentItemsImage: '.related-content-items li img',
    relatedContentItemsTitle: '.related-content-items li',
    relatedContentHeading_aww_wd: '.content-body__related-content-heading',
    relatedContentItemsImage_aww_wd: '.content-body__related-teaser img',
    relatedContentItemsTitle_aww_wd: '.content-body__related-teaser',
    relatedContentItemsImage_food: '.content-body__related .teaser__image',
    relatedContentItemsTitle_food: '.content-body__related .teaser__body',
    bodyGallery:'.content-body__gallery-link a',
    bodyImgCaption:'.content-body__inline-image-caption',
    heroVideo: '.article__main-hero-video',
    heroVideoPlaylist: '.article__main-hero .video-playlist-container',
    heroVideoPlaylistItem: '.article__main-hero .vjs-playlist-loaded li',
    heroVideoPlaylistThumbnail: '.article__main-hero .video-playlist-container .vjs-playlist-item img',
    heroVideoPlaylistTitle: '.article__main-hero .video-playlist-container .vjs-playlist-name',
    heroVideoPlayButton: '.article__main-hero button.vjs-big-play-button',
    heroVideoControlBar: '.article__main-hero .vjs-control-bar button',
    heroVideoProgress: '.article__main-hero .vjs-progress-control .vjs-slider-horizontal',
    heroVideoFood: '.article__hero-wrapper--video',
    heroImg: '.article__main-hero picture',
    heroImgCaption: '.article__main-hero .article_image-caption',
    heroImgFood: '.article__hero-wrapper--img',
    lhrFeedItems: 'ul.feed__items li.feed-item',
    lhrFeedTitles: 'ul.feed__items a.feed-item__body-title',
    lhrFeedImgs: 'ul.feed__items a.teaser__image',
    lhrFeedOneTitle: '.feed__container li.feed-item:nth-child(1) a.feed-item__body-title',
    lhrFeedOneImg: '.feed__container li.feed-item:nth-child(1) a.teaser__image',
    lhrFeedOneSource: '.feed__container li.feed-item:nth-child(1) .feed-item__source',
    lhrFeed: '.feed',
    bodyVideo: '.content-body__inline-video',
    bodyTips:'.content-body__tips',
    Bodycomp:'.content-body__competition iframe',
    relatedTags: 'section.article__tags ul.related-tags li',
    relatedWnTags: 'span.article__tag', // this tag is for WD, AWW only
    authorWn: '.article__author-name',  // this tag is for WD, AWW only
    authorText: '.article .article-header-author span:last-child',
    twitterEmb1: '#twitter-widget-0',
    instagramEmb1: '.instagram-media',
    facebookEmb1: '.fb-post.fb_iframe_widget',
    playbuzzEmb1: '.content-body__embed--playbuzz > div',
    videoEmbArry: '.content-body__embed-video-container iframe',
    whooshkaEmb: '.content-body__embed-whooshka iframe',
    wirewaxEmb: '.content-body__embed-wirewax iframe',
    linklayEmb: '.content-body__embed-linklay iframe',
    giphyEmb: '.content-body__embed.content-body__embed--giphy img',
    outbrain: '.article .OUTBRAIN',
    reactionText: ".reactions-leader",
    smileBtn: ".reaction-button--smile",
    wd_lhrFeedHeader: '.article__listing .feed__header',
    wd_lhrFeedImage: '.article__listing .feed__image',
    wd_lhrFeedImageLink: '.article__listing .feed__item-image a',
    wd_lhrFeedLongTitle: '.article__listing .feed__item-heading',
    wd_lhrFeedLongTitleLink: '.article__listing .feed__item-heading a',
    wd_lhrFeedSubsection: '.article__listing .feed__subSection',
    wd_lhrFeedSubsectionLink: '.article__listing .feed__subSection a',
    wd_lhrFeedDate: '.article__listing .feed__item-date',
    relatedPolarFeed: '.related-content-items > .polar-feed-item',
    imageRevealer: '.content-body .image-revealer',
    imageRevealerLeftImg: '.content-body .image-revealer__left img',
    imageRevealerRightImg: '.content-body .image-revealer__right img',
    feedCoursel: '.content-body__feed-carousel-content'
};

module.exports = article_widget;
