var brand_listing_widget = {
    brandLogo: ".brand-section__logo-image",
    brandHeroTeaser: 'article.teaser--hero',
    brandArticle: "article.teaser:not(.teaser--hero)",
    brandArticleImg: ".brand-section li:nth-child(2) img",
    brandArticleImgLink: ".brand-section li:nth-child(2) a.teaser__image",
    brandArticleTitle: ".brand-section li:nth-child(2) .teaser__title a",
    brandArticleTag: ".brand-section li:nth-child(2) .teaser__tags",
    brandArticlePrimaryTagLink: ".brand-section li:nth-child(3) .teaser__tags .tag-primary a",
    brandArticleSecondaryTagLink: ".brand-section li:nth-child(3) .teaser__tags .tag-secondary a",
    brandSubscribeUnder: ".brand-subscribe.hide-for-xlarge-up",
    brandSubscribeUnderImg: ".brand-subscribe.hide-for-xlarge-up img",
    brandSubscribeUnderImgLink: ".brand-subscribe.hide-for-xlarge-up a.teaser__image",
    brandSubscribeUnderTitle: ".brand-subscribe.hide-for-xlarge-up .teaser__title a",
    brandSubscribeFront: ".brand-subscribe.show-for-xlarge-up",
    brandSubscribeFrontImg: ".brand-subscribe.show-for-xlarge-up img",
    brandSubscribeFrontImgLink: ".brand-subscribe.show-for-xlarge-up a.teaser__image",
    brandSubscribeFrontTitle: ".brand-subscribe.show-for-xlarge-up .teaser__title a",
    brandSocial: ".brand-social",
    recommendationsHeading: ".dacrm-recommendations__heading",
    brandStickyMobileBanner: '.sticky-block.sticky-block--at-bottom.sticky-block--out-of-view',
    newsletterSignUpBtnDesktop: 'section > div > div > .carriage .newsletter-subscribe__button a',
    newsletterSignUpBtnMobile: '.hide-for-large-up .newsletter-subscribe__button a',
};

module.exports = brand_listing_widget;
