const listingWidget = {
    // section classes
    fullWidthGallerySection: '.full-width-gallery-section',
    companyProfileSection: '.company-profile-section',
    productSection: '.product-section',
    galleryLinkSection: '.gallery-link-section',
    testimonialSection: '.testimonial-section',
    featuredArticleSection: '.featured-article-section',
    contactSection: '.contact-section',

    // generic component classes
    heading: '.heading',
    mediaSlider: '.media-slider',
    scrollDownButton: '.scroll-down-button',
    imageGallery: '.listing-image-gallery',
    imageGallerySlide: '.image-gallery-slide',
    galleryModalButton: '.gallery-link-section__gallery-button',
    galleryModal: '.listing-gallery-modal',
    galleryModalHeader: '.listing-gallery-modal__header',
    galleryModalTitle: '.listing-gallery-modal__title',
    galleryModalImageWrapper: '.listing-gallery-modal__image-wrapper',
    galleryModalImage: '.listing-gallery-modal__image',
    modalClose: '.listing-gallery-modal__close-button',
    brandLogo: '.listing-brand-logo',
    brandLogoImg: '.listing-brand-logo__image',
    summary: '.summary',
    summaryAddress: '.summary__address',
    summaryCopy: '.summary__copy',
    summarySubheading: '.summary__sub-heading',
    socialLinks: 'social-icons',
    facebookIcon: '.social-icon--facebook',
    twitterIcon: '.social-icon--twitter',
    pinterestIcon: '.social-icon--pinterest',
    instagramIcon: '.social-icon--instagram',
    testimonialCard: '.testimonial-card',
    featuredArticleCard: '.featured-article-card',
    featuredArticleCardGalleryWrapper: '.featured-article-card__image-preview',
    featuredArticleCardLinkButton: '.featured-article-card__link-button',
    featuredArticleCardTitle: '.featured-article-card__article-title',
    featuredArticleCardSummary: '.featured-article-card__article-summary',
    featuredArticleCardSource: '.featured-article-card__article-source',
    featuredArticleCardDateCreated: '.featured-article-card__date-created',
    productCard: '.product-card',
    contactForm: '.contact-form',
    contactCard: '.contact-card',
    breadCrumbs: '.breadcrumbs',
    header: '.listing-header',
    contactHeading: '.contact-section__heading',
    contactSubheading: '.contact-section__sub-heading',
    contactEmailField: '.contact-form__text-input#email',
    contactMessageField: '.contact-form__textarea#message',
    contactSubmitButton: '.contact-form__button',
    contactCardWebAddress: '.contact-card__list-item--web-address',
    contactCardWebAddressIcon: '.icon--globe-icon',
    contactCardStreetAddress: '.contact-card__list-item--street-address',
    contactCardStreetAddressIcon: '.icon--home-icon',
    contactCardPhone: '.contact-card__list-item--phone',
    contactCardPhoneIcon: '.icon--phone-icon',
    contactCardText: '.contact-card__list-item-text',
    contactCardLink: '.contact-card__list-item-link'
};

export default listingWidget;
