instrumentation:
    excludes: [
        'start.js',
        '**/automation/**',
        'dist/**',
        'node_modules/**',
        'test/**',
        '**/config/**',
        'app/server/server.js',
        'app/server/bff.js',
        'app/client.js',
        'app/app.js',
        'app/breakpoints.js',
        'stubs/**'
    ]
    extensions: ['.js', '.jsx']
